import { msg } from '@lingui/core/macro';
import type { Metadata } from 'next';

import { getI18nInstance, initI18n } from '@/i18n';
import { LinguiClientProvider } from '@/LinguiClientProvider';

import './globals.css';

export async function generateMetadata(): Promise<Metadata> {
  const i18n = await getI18nInstance();

  return {
    title: 'Create Next App',
    description: i18n._(msg`Generated by create next app`),
  };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const i18n = await getI18nInstance();
  await initI18n();

  return (
    <html lang={i18n.locale}>
      <body>
        <LinguiClientProvider
          initialLocale={i18n.locale}
          initialMessages={i18n.messages}
        >
          {children}
        </LinguiClientProvider>
      </body>
    </html>
  );
}
